version: "3.8"

services:
  database:
    container_name: postgres_db
    image: postgres:17-alpine3.19
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  app:
    container_name: go_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
    restart: on-failure


volumes:
  postgres_data:

