version: "3"

services:
  database:
    container_name: avito_postgres_db
    image: postgres:17-alpine3.19
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"


volumes:
  postgres_data:

